import React from 'react';

import ContactForm from '@/components/contact-forms/ContactForm.component';
import styles from './contact.module.css';

export const metadata = {
	title: 'Contact Us',
	description: 'Generated by Rock Digital',
};

const Contact = () => {
	return (
		<div>
			<div className={styles.contact_container}>
				<div className={styles.contact_img_container}>
					<div id={styles['contact_img_container_text']}>CONTACT US</div>
				</div>
				<ContactForm />
			</div>
		</div>
	);
};

export default Contact;
