import Navigation from '@/components/navigation/navigation.component';
import BootstrapClient from '@/components/bootstrap_client/BootstrapClient';

import 'bootstrap/dist/css/bootstrap.css';
import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<Navigation />
				{children}
        <BootstrapClient  />
			</body>
		</html>
	);
}
